[sms-in]
exten => _.,1,NoOp(Inbound SMS received)

same => n,Set(NUMBER_TO=${MESSAGE_DATA(X-SMS-To)})
same => n,Set(HOST_TO=${CUT(MESSAGE(to),@,2)})
same => n,Set(ACTUAL_FROM=${MESSAGE(from)})
same => n,Set(ACTUAL_TO=pjsip:${NUMBER_TO}@${HOST_TO})
same => n,Set(MSG_BODY=${MESSAGE(body)})

same => n,MessageSend(${ACTUAL_TO},${ACTUAL_FROM})
same => n,NoOp(Status ${MESSAGE_SEND_STATUS})

same => n,GotoIf($["${MESSAGE_SEND_STATUS}"="SUCCESS"]?done)

same => n,AGI(sms_queue_insert.py)
same => n,NoOp(SMS queued)

same => n(done),Hangup()
